// GENERATED by scripts/build-catalog.mjs — do not edit by hand.
// Source: Hugging Face public API. Re-run the script to refresh.
export const GENERATED_AT = "2026-07-15T02:48:59.669Z";
export const SNAPSHOT = [
  {
    "id": "hf:Jackrong/Qwen3.5-4B-Claude-4.6-Opus-Reasoning-Distilled-GGUF:Q2_K",
    "family": "Qwen3.5-4B-Claude-4.6-Opus-Reasoning-Distilled",
    "name": "Qwen3.5-4B-Claude-4.6-Opus-Reasoning-Distilled",
    "task": "reasoning",
    "params": 4,
    "quant": "Q2_K",
    "sizeBytes": 1797501760,
    "sidecarBytes": 675568864,
    "modalities": [
      "text",
      "image"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "Jackrong/Qwen3.5-4B-Claude-4.6-Opus-Reasoning-Distilled-GGUF",
      "path": "Qwen3.5-4B.Q2_K.gguf"
    }
  },
  {
    "id": "hf:Jackrong/Qwen3.5-4B-Claude-4.6-Opus-Reasoning-Distilled-GGUF:Q3_K_L",
    "family": "Qwen3.5-4B-Claude-4.6-Opus-Reasoning-Distilled",
    "name": "Qwen3.5-4B-Claude-4.6-Opus-Reasoning-Distilled",
    "task": "reasoning",
    "params": 4,
    "quant": "Q3_K_L",
    "sizeBytes": 2358397760,
    "sidecarBytes": 675568864,
    "modalities": [
      "text",
      "image"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "Jackrong/Qwen3.5-4B-Claude-4.6-Opus-Reasoning-Distilled-GGUF",
      "path": "Qwen3.5-4B.Q3_K_L.gguf"
    }
  },
  {
    "id": "hf:Jackrong/Qwen3.5-4B-Claude-4.6-Opus-Reasoning-Distilled-GGUF:Q3_K_M",
    "family": "Qwen3.5-4B-Claude-4.6-Opus-Reasoning-Distilled",
    "name": "Qwen3.5-4B-Claude-4.6-Opus-Reasoning-Distilled",
    "task": "reasoning",
    "params": 4,
    "quant": "Q3_K_M",
    "sizeBytes": 2257472320,
    "sidecarBytes": 675568864,
    "modalities": [
      "text",
      "image"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "Jackrong/Qwen3.5-4B-Claude-4.6-Opus-Reasoning-Distilled-GGUF",
      "path": "Qwen3.5-4B.Q3_K_M.gguf"
    }
  },
  {
    "id": "hf:Jackrong/Qwen3.5-4B-Claude-4.6-Opus-Reasoning-Distilled-GGUF:Q3_K_S",
    "family": "Qwen3.5-4B-Claude-4.6-Opus-Reasoning-Distilled",
    "name": "Qwen3.5-4B-Claude-4.6-Opus-Reasoning-Distilled",
    "task": "reasoning",
    "params": 4,
    "quant": "Q3_K_S",
    "sizeBytes": 2069875520,
    "sidecarBytes": 675568864,
    "modalities": [
      "text",
      "image"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "Jackrong/Qwen3.5-4B-Claude-4.6-Opus-Reasoning-Distilled-GGUF",
      "path": "Qwen3.5-4B.Q3_K_S.gguf"
    }
  },
  {
    "id": "hf:Jackrong/Qwen3.5-4B-Claude-4.6-Opus-Reasoning-Distilled-GGUF:Q4_K_M",
    "family": "Qwen3.5-4B-Claude-4.6-Opus-Reasoning-Distilled",
    "name": "Qwen3.5-4B-Claude-4.6-Opus-Reasoning-Distilled",
    "task": "reasoning",
    "params": 4,
    "quant": "Q4_K_M",
    "sizeBytes": 2707510080,
    "sidecarBytes": 675568864,
    "modalities": [
      "text",
      "image"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "Jackrong/Qwen3.5-4B-Claude-4.6-Opus-Reasoning-Distilled-GGUF",
      "path": "Qwen3.5-4B.Q4_K_M.gguf"
    }
  },
  {
    "id": "hf:Jackrong/Qwen3.5-4B-Claude-4.6-Opus-Reasoning-Distilled-GGUF:Q4_K_S",
    "family": "Qwen3.5-4B-Claude-4.6-Opus-Reasoning-Distilled",
    "name": "Qwen3.5-4B-Claude-4.6-Opus-Reasoning-Distilled",
    "task": "reasoning",
    "params": 4,
    "quant": "Q4_K_S",
    "sizeBytes": 2557002560,
    "sidecarBytes": 675568864,
    "modalities": [
      "text",
      "image"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "Jackrong/Qwen3.5-4B-Claude-4.6-Opus-Reasoning-Distilled-GGUF",
      "path": "Qwen3.5-4B.Q4_K_S.gguf"
    }
  },
  {
    "id": "hf:Jackrong/Qwen3.5-4B-Claude-4.6-Opus-Reasoning-Distilled-GGUF:Q5_K_M",
    "family": "Qwen3.5-4B-Claude-4.6-Opus-Reasoning-Distilled",
    "name": "Qwen3.5-4B-Claude-4.6-Opus-Reasoning-Distilled",
    "task": "reasoning",
    "params": 4,
    "quant": "Q5_K_M",
    "sizeBytes": 3108754240,
    "sidecarBytes": 675568864,
    "modalities": [
      "text",
      "image"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "Jackrong/Qwen3.5-4B-Claude-4.6-Opus-Reasoning-Distilled-GGUF",
      "path": "Qwen3.5-4B.Q5_K_M.gguf"
    }
  },
  {
    "id": "hf:Jackrong/Qwen3.5-4B-Claude-4.6-Opus-Reasoning-Distilled-GGUF:Q5_K_S",
    "family": "Qwen3.5-4B-Claude-4.6-Opus-Reasoning-Distilled",
    "name": "Qwen3.5-4B-Claude-4.6-Opus-Reasoning-Distilled",
    "task": "reasoning",
    "params": 4,
    "quant": "Q5_K_S",
    "sizeBytes": 2990031680,
    "sidecarBytes": 675568864,
    "modalities": [
      "text",
      "image"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "Jackrong/Qwen3.5-4B-Claude-4.6-Opus-Reasoning-Distilled-GGUF",
      "path": "Qwen3.5-4B.Q5_K_S.gguf"
    }
  },
  {
    "id": "hf:Jackrong/Qwen3.5-4B-Claude-4.6-Opus-Reasoning-Distilled-GGUF:Q6_K",
    "family": "Qwen3.5-4B-Claude-4.6-Opus-Reasoning-Distilled",
    "name": "Qwen3.5-4B-Claude-4.6-Opus-Reasoning-Distilled",
    "task": "reasoning",
    "params": 4,
    "quant": "Q6_K",
    "sizeBytes": 3464051520,
    "sidecarBytes": 675568864,
    "modalities": [
      "text",
      "image"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "Jackrong/Qwen3.5-4B-Claude-4.6-Opus-Reasoning-Distilled-GGUF",
      "path": "Qwen3.5-4B.Q6_K.gguf"
    }
  },
  {
    "id": "hf:Jackrong/Qwen3.5-4B-Claude-4.6-Opus-Reasoning-Distilled-GGUF:Q8_0",
    "family": "Qwen3.5-4B-Claude-4.6-Opus-Reasoning-Distilled",
    "name": "Qwen3.5-4B-Claude-4.6-Opus-Reasoning-Distilled",
    "task": "reasoning",
    "params": 4,
    "quant": "Q8_0",
    "sizeBytes": 4482399040,
    "sidecarBytes": 675568864,
    "modalities": [
      "text",
      "image"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "Jackrong/Qwen3.5-4B-Claude-4.6-Opus-Reasoning-Distilled-GGUF",
      "path": "Qwen3.5-4B.Q8_0.gguf"
    }
  },
  {
    "id": "hf:LiquidAI/LFM2.5-1.2B-Instruct-GGUF:Q4_0",
    "family": "LFM2.5-1.2B-Instruct",
    "name": "LFM2.5-1.2B-Instruct",
    "task": "chat",
    "params": 1.2,
    "quant": "Q4_0",
    "sizeBytes": 695751488,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "LiquidAI/LFM2.5-1.2B-Instruct-GGUF",
      "path": "LFM2.5-1.2B-Instruct-Q4_0.gguf"
    }
  },
  {
    "id": "hf:LiquidAI/LFM2.5-1.2B-Instruct-GGUF:Q4_K_M",
    "family": "LFM2.5-1.2B-Instruct",
    "name": "LFM2.5-1.2B-Instruct",
    "task": "chat",
    "params": 1.2,
    "quant": "Q4_K_M",
    "sizeBytes": 730895168,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "LiquidAI/LFM2.5-1.2B-Instruct-GGUF",
      "path": "LFM2.5-1.2B-Instruct-Q4_K_M.gguf"
    }
  },
  {
    "id": "hf:LiquidAI/LFM2.5-1.2B-Instruct-GGUF:Q5_K_M",
    "family": "LFM2.5-1.2B-Instruct",
    "name": "LFM2.5-1.2B-Instruct",
    "task": "chat",
    "params": 1.2,
    "quant": "Q5_K_M",
    "sizeBytes": 843354944,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "LiquidAI/LFM2.5-1.2B-Instruct-GGUF",
      "path": "LFM2.5-1.2B-Instruct-Q5_K_M.gguf"
    }
  },
  {
    "id": "hf:LiquidAI/LFM2.5-1.2B-Instruct-GGUF:Q6_K",
    "family": "LFM2.5-1.2B-Instruct",
    "name": "LFM2.5-1.2B-Instruct",
    "task": "chat",
    "params": 1.2,
    "quant": "Q6_K",
    "sizeBytes": 962843456,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "LiquidAI/LFM2.5-1.2B-Instruct-GGUF",
      "path": "LFM2.5-1.2B-Instruct-Q6_K.gguf"
    }
  },
  {
    "id": "hf:LiquidAI/LFM2.5-1.2B-Instruct-GGUF:Q8_0",
    "family": "LFM2.5-1.2B-Instruct",
    "name": "LFM2.5-1.2B-Instruct",
    "task": "chat",
    "params": 1.2,
    "quant": "Q8_0",
    "sizeBytes": 1246253888,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "LiquidAI/LFM2.5-1.2B-Instruct-GGUF",
      "path": "LFM2.5-1.2B-Instruct-Q8_0.gguf"
    }
  },
  {
    "id": "hf:MaziyarPanahi/Ministral-3-14B-Reasoning-2512-GGUF:Q2_K",
    "family": "Ministral-3-14B-Reasoning-2512",
    "name": "Ministral-3-14B-Reasoning-2512",
    "task": "reasoning",
    "params": 14,
    "quant": "Q2_K",
    "sizeBytes": 5246529152,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "MaziyarPanahi/Ministral-3-14B-Reasoning-2512-GGUF",
      "path": "Ministral-3-14B-Reasoning-2512.Q2_K.gguf"
    }
  },
  {
    "id": "hf:MaziyarPanahi/Ministral-3-14B-Reasoning-2512-GGUF:Q3_K_L",
    "family": "Ministral-3-14B-Reasoning-2512",
    "name": "Ministral-3-14B-Reasoning-2512",
    "task": "reasoning",
    "params": 14,
    "quant": "Q3_K_L",
    "sizeBytes": 7210315392,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "MaziyarPanahi/Ministral-3-14B-Reasoning-2512-GGUF",
      "path": "Ministral-3-14B-Reasoning-2512.Q3_K_L.gguf"
    }
  },
  {
    "id": "hf:MaziyarPanahi/Ministral-3-14B-Reasoning-2512-GGUF:Q3_K_M",
    "family": "Ministral-3-14B-Reasoning-2512",
    "name": "Ministral-3-14B-Reasoning-2512",
    "task": "reasoning",
    "params": 14,
    "quant": "Q3_K_M",
    "sizeBytes": 6682095232,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "MaziyarPanahi/Ministral-3-14B-Reasoning-2512-GGUF",
      "path": "Ministral-3-14B-Reasoning-2512.Q3_K_M.gguf"
    }
  },
  {
    "id": "hf:MaziyarPanahi/Ministral-3-14B-Reasoning-2512-GGUF:Q4_K_M",
    "family": "Ministral-3-14B-Reasoning-2512",
    "name": "Ministral-3-14B-Reasoning-2512",
    "task": "reasoning",
    "params": 14,
    "quant": "Q4_K_M",
    "sizeBytes": 8239066752,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "MaziyarPanahi/Ministral-3-14B-Reasoning-2512-GGUF",
      "path": "Ministral-3-14B-Reasoning-2512.Q4_K_M.gguf"
    }
  },
  {
    "id": "hf:MaziyarPanahi/Ministral-3-14B-Reasoning-2512-GGUF:Q5_K_M",
    "family": "Ministral-3-14B-Reasoning-2512",
    "name": "Ministral-3-14B-Reasoning-2512",
    "task": "reasoning",
    "params": 14,
    "quant": "Q5_K_M",
    "sizeBytes": 9620565632,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "MaziyarPanahi/Ministral-3-14B-Reasoning-2512-GGUF",
      "path": "Ministral-3-14B-Reasoning-2512.Q5_K_M.gguf"
    }
  },
  {
    "id": "hf:MaziyarPanahi/Ministral-3-14B-Reasoning-2512-GGUF:Q6_K",
    "family": "Ministral-3-14B-Reasoning-2512",
    "name": "Ministral-3-14B-Reasoning-2512",
    "task": "reasoning",
    "params": 14,
    "quant": "Q6_K",
    "sizeBytes": 11088408192,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "MaziyarPanahi/Ministral-3-14B-Reasoning-2512-GGUF",
      "path": "Ministral-3-14B-Reasoning-2512.Q6_K.gguf"
    }
  },
  {
    "id": "hf:MaziyarPanahi/Ministral-3-3B-Reasoning-2512-GGUF:Q2_K",
    "family": "Ministral-3-3B-Reasoning-2512",
    "name": "Ministral-3-3B-Reasoning-2512",
    "task": "reasoning",
    "params": 3,
    "quant": "Q2_K",
    "sizeBytes": 1458958528,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "MaziyarPanahi/Ministral-3-3B-Reasoning-2512-GGUF",
      "path": "Ministral-3-3B-Reasoning-2512.Q2_K.gguf"
    }
  },
  {
    "id": "hf:MaziyarPanahi/Ministral-3-3B-Reasoning-2512-GGUF:Q3_K_L",
    "family": "Ministral-3-3B-Reasoning-2512",
    "name": "Ministral-3-3B-Reasoning-2512",
    "task": "reasoning",
    "params": 3,
    "quant": "Q3_K_L",
    "sizeBytes": 1934356672,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "MaziyarPanahi/Ministral-3-3B-Reasoning-2512-GGUF",
      "path": "Ministral-3-3B-Reasoning-2512.Q3_K_L.gguf"
    }
  },
  {
    "id": "hf:MaziyarPanahi/Ministral-3-3B-Reasoning-2512-GGUF:Q3_K_M",
    "family": "Ministral-3-3B-Reasoning-2512",
    "name": "Ministral-3-3B-Reasoning-2512",
    "task": "reasoning",
    "params": 3,
    "quant": "Q3_K_M",
    "sizeBytes": 1795551424,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "MaziyarPanahi/Ministral-3-3B-Reasoning-2512-GGUF",
      "path": "Ministral-3-3B-Reasoning-2512.Q3_K_M.gguf"
    }
  },
  {
    "id": "hf:MaziyarPanahi/Ministral-3-3B-Reasoning-2512-GGUF:Q4_K_M",
    "family": "Ministral-3-3B-Reasoning-2512",
    "name": "Ministral-3-3B-Reasoning-2512",
    "task": "reasoning",
    "params": 3,
    "quant": "Q4_K_M",
    "sizeBytes": 2146496704,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "MaziyarPanahi/Ministral-3-3B-Reasoning-2512-GGUF",
      "path": "Ministral-3-3B-Reasoning-2512.Q4_K_M.gguf"
    }
  },
  {
    "id": "hf:MaziyarPanahi/Ministral-3-3B-Reasoning-2512-GGUF:Q5_K_M",
    "family": "Ministral-3-3B-Reasoning-2512",
    "name": "Ministral-3-3B-Reasoning-2512",
    "task": "reasoning",
    "params": 3,
    "quant": "Q5_K_M",
    "sizeBytes": 2473652416,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "MaziyarPanahi/Ministral-3-3B-Reasoning-2512-GGUF",
      "path": "Ministral-3-3B-Reasoning-2512.Q5_K_M.gguf"
    }
  },
  {
    "id": "hf:MaziyarPanahi/Ministral-3-3B-Reasoning-2512-GGUF:Q6_K",
    "family": "Ministral-3-3B-Reasoning-2512",
    "name": "Ministral-3-3B-Reasoning-2512",
    "task": "reasoning",
    "params": 3,
    "quant": "Q6_K",
    "sizeBytes": 2821255360,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "MaziyarPanahi/Ministral-3-3B-Reasoning-2512-GGUF",
      "path": "Ministral-3-3B-Reasoning-2512.Q6_K.gguf"
    }
  },
  {
    "id": "hf:MaziyarPanahi/Yi-Coder-1.5B-Chat-GGUF:IQ1_M",
    "family": "Yi-Coder-1.5B-Chat",
    "name": "Yi-Coder-1.5B-Chat",
    "task": "code",
    "params": 1.5,
    "quant": "IQ1_M",
    "sizeBytes": 508567744,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "MaziyarPanahi/Yi-Coder-1.5B-Chat-GGUF",
      "path": "Yi-Coder-1.5B-Chat.IQ1_M.gguf"
    }
  },
  {
    "id": "hf:MaziyarPanahi/Yi-Coder-1.5B-Chat-GGUF:IQ1_S",
    "family": "Yi-Coder-1.5B-Chat",
    "name": "Yi-Coder-1.5B-Chat",
    "task": "code",
    "params": 1.5,
    "quant": "IQ1_S",
    "sizeBytes": 491167936,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "MaziyarPanahi/Yi-Coder-1.5B-Chat-GGUF",
      "path": "Yi-Coder-1.5B-Chat.IQ1_S.gguf"
    }
  },
  {
    "id": "hf:MaziyarPanahi/Yi-Coder-1.5B-Chat-GGUF:IQ2_XS",
    "family": "Yi-Coder-1.5B-Chat",
    "name": "Yi-Coder-1.5B-Chat",
    "task": "code",
    "params": 1.5,
    "quant": "IQ2_XS",
    "sizeBytes": 563912896,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "MaziyarPanahi/Yi-Coder-1.5B-Chat-GGUF",
      "path": "Yi-Coder-1.5B-Chat.IQ2_XS.gguf"
    }
  },
  {
    "id": "hf:MaziyarPanahi/Yi-Coder-1.5B-Chat-GGUF:IQ3_XS",
    "family": "Yi-Coder-1.5B-Chat",
    "name": "Yi-Coder-1.5B-Chat",
    "task": "code",
    "params": 1.5,
    "quant": "IQ3_XS",
    "sizeBytes": 694952128,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "MaziyarPanahi/Yi-Coder-1.5B-Chat-GGUF",
      "path": "Yi-Coder-1.5B-Chat.IQ3_XS.gguf"
    }
  },
  {
    "id": "hf:MaziyarPanahi/Yi-Coder-1.5B-Chat-GGUF:IQ4_XS",
    "family": "Yi-Coder-1.5B-Chat",
    "name": "Yi-Coder-1.5B-Chat",
    "task": "code",
    "params": 1.5,
    "quant": "IQ4_XS",
    "sizeBytes": 832569536,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "MaziyarPanahi/Yi-Coder-1.5B-Chat-GGUF",
      "path": "Yi-Coder-1.5B-Chat.IQ4_XS.gguf"
    }
  },
  {
    "id": "hf:MaziyarPanahi/Yi-Coder-1.5B-Chat-GGUF:Q2_K",
    "family": "Yi-Coder-1.5B-Chat",
    "name": "Yi-Coder-1.5B-Chat",
    "task": "code",
    "params": 1.5,
    "quant": "Q2_K",
    "sizeBytes": 634699968,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "MaziyarPanahi/Yi-Coder-1.5B-Chat-GGUF",
      "path": "Yi-Coder-1.5B-Chat.Q2_K.gguf"
    }
  },
  {
    "id": "hf:MaziyarPanahi/Yi-Coder-1.5B-Chat-GGUF:Q3_K_L",
    "family": "Yi-Coder-1.5B-Chat",
    "name": "Yi-Coder-1.5B-Chat",
    "task": "code",
    "params": 1.5,
    "quant": "Q3_K_L",
    "sizeBytes": 826040512,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "MaziyarPanahi/Yi-Coder-1.5B-Chat-GGUF",
      "path": "Yi-Coder-1.5B-Chat.Q3_K_L.gguf"
    }
  },
  {
    "id": "hf:MaziyarPanahi/Yi-Coder-1.5B-Chat-GGUF:Q3_K_M",
    "family": "Yi-Coder-1.5B-Chat",
    "name": "Yi-Coder-1.5B-Chat",
    "task": "code",
    "params": 1.5,
    "quant": "Q3_K_M",
    "sizeBytes": 785719488,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "MaziyarPanahi/Yi-Coder-1.5B-Chat-GGUF",
      "path": "Yi-Coder-1.5B-Chat.Q3_K_M.gguf"
    }
  },
  {
    "id": "hf:MaziyarPanahi/Yi-Coder-1.5B-Chat-GGUF:Q3_K_S",
    "family": "Yi-Coder-1.5B-Chat",
    "name": "Yi-Coder-1.5B-Chat",
    "task": "code",
    "params": 1.5,
    "quant": "Q3_K_S",
    "sizeBytes": 723411136,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "MaziyarPanahi/Yi-Coder-1.5B-Chat-GGUF",
      "path": "Yi-Coder-1.5B-Chat.Q3_K_S.gguf"
    }
  },
  {
    "id": "hf:MaziyarPanahi/Yi-Coder-1.5B-Chat-GGUF:Q4_K_M",
    "family": "Yi-Coder-1.5B-Chat",
    "name": "Yi-Coder-1.5B-Chat",
    "task": "code",
    "params": 1.5,
    "quant": "Q4_K_M",
    "sizeBytes": 963674304,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "MaziyarPanahi/Yi-Coder-1.5B-Chat-GGUF",
      "path": "Yi-Coder-1.5B-Chat.Q4_K_M.gguf"
    }
  },
  {
    "id": "hf:MaziyarPanahi/Yi-Coder-1.5B-Chat-GGUF:Q4_K_S",
    "family": "Yi-Coder-1.5B-Chat",
    "name": "Yi-Coder-1.5B-Chat",
    "task": "code",
    "params": 1.5,
    "quant": "Q4_K_S",
    "sizeBytes": 904184000,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "MaziyarPanahi/Yi-Coder-1.5B-Chat-GGUF",
      "path": "Yi-Coder-1.5B-Chat.Q4_K_S.gguf"
    }
  },
  {
    "id": "hf:MaziyarPanahi/Yi-Coder-1.5B-Chat-GGUF:Q5_K_M",
    "family": "Yi-Coder-1.5B-Chat",
    "name": "Yi-Coder-1.5B-Chat",
    "task": "code",
    "params": 1.5,
    "quant": "Q5_K_M",
    "sizeBytes": 1100185792,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "MaziyarPanahi/Yi-Coder-1.5B-Chat-GGUF",
      "path": "Yi-Coder-1.5B-Chat.Q5_K_M.gguf"
    }
  },
  {
    "id": "hf:MaziyarPanahi/Yi-Coder-1.5B-Chat-GGUF:Q5_K_S",
    "family": "Yi-Coder-1.5B-Chat",
    "name": "Yi-Coder-1.5B-Chat",
    "task": "code",
    "params": 1.5,
    "quant": "Q5_K_S",
    "sizeBytes": 1051230400,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "MaziyarPanahi/Yi-Coder-1.5B-Chat-GGUF",
      "path": "Yi-Coder-1.5B-Chat.Q5_K_S.gguf"
    }
  },
  {
    "id": "hf:Qwen/Qwen2.5-Coder-32B-Instruct-GGUF:Q2_K",
    "family": "Qwen2.5-Coder-32B-Instruct",
    "name": "Qwen2.5-Coder-32B-Instruct",
    "task": "code",
    "params": 32,
    "quant": "Q2_K",
    "sizeBytes": 12313098432,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "Qwen/Qwen2.5-Coder-32B-Instruct-GGUF",
      "path": "qwen2.5-coder-32b-instruct-q2_k.gguf"
    }
  },
  {
    "id": "hf:Qwen/Qwen2.5-Coder-32B-Instruct-GGUF:Q3_K_M",
    "family": "Qwen2.5-Coder-32B-Instruct",
    "name": "Qwen2.5-Coder-32B-Instruct",
    "task": "code",
    "params": 32,
    "quant": "Q3_K_M",
    "sizeBytes": 15935047872,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "Qwen/Qwen2.5-Coder-32B-Instruct-GGUF",
      "path": "qwen2.5-coder-32b-instruct-q3_k_m.gguf"
    }
  },
  {
    "id": "hf:Qwen/Qwen2.5-Coder-32B-Instruct-GGUF:Q4_0",
    "family": "Qwen2.5-Coder-32B-Instruct",
    "name": "Qwen2.5-Coder-32B-Instruct",
    "task": "code",
    "params": 32,
    "quant": "Q4_0",
    "sizeBytes": 18640230592,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "Qwen/Qwen2.5-Coder-32B-Instruct-GGUF",
      "path": "qwen2.5-coder-32b-instruct-q4_0.gguf"
    }
  },
  {
    "id": "hf:Qwen/Qwen2.5-Coder-32B-Instruct-GGUF:Q4_K_M",
    "family": "Qwen2.5-Coder-32B-Instruct",
    "name": "Qwen2.5-Coder-32B-Instruct",
    "task": "code",
    "params": 32,
    "quant": "Q4_K_M",
    "sizeBytes": 19851335872,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "Qwen/Qwen2.5-Coder-32B-Instruct-GGUF",
      "path": "qwen2.5-coder-32b-instruct-q4_k_m.gguf"
    }
  },
  {
    "id": "hf:Qwen/Qwen2.5-Coder-32B-Instruct-GGUF:Q5_0",
    "family": "Qwen2.5-Coder-32B-Instruct",
    "name": "Qwen2.5-Coder-32B-Instruct",
    "task": "code",
    "params": 32,
    "quant": "Q5_0",
    "sizeBytes": 22638254272,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "Qwen/Qwen2.5-Coder-32B-Instruct-GGUF",
      "path": "qwen2.5-coder-32b-instruct-q5_0.gguf"
    }
  },
  {
    "id": "hf:Qwen/Qwen2.5-Coder-32B-Instruct-GGUF:Q5_K_M",
    "family": "Qwen2.5-Coder-32B-Instruct",
    "name": "Qwen2.5-Coder-32B-Instruct",
    "task": "code",
    "params": 32,
    "quant": "Q5_K_M",
    "sizeBytes": 23262156992,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "Qwen/Qwen2.5-Coder-32B-Instruct-GGUF",
      "path": "qwen2.5-coder-32b-instruct-q5_k_m.gguf"
    }
  },
  {
    "id": "hf:Qwen/Qwen2.5-Coder-32B-Instruct-GGUF:Q6_K",
    "family": "Qwen2.5-Coder-32B-Instruct",
    "name": "Qwen2.5-Coder-32B-Instruct",
    "task": "code",
    "params": 32,
    "quant": "Q6_K",
    "sizeBytes": 26886154432,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "Qwen/Qwen2.5-Coder-32B-Instruct-GGUF",
      "path": "qwen2.5-coder-32b-instruct-q6_k.gguf"
    }
  },
  {
    "id": "hf:Qwen/Qwen2.5-Coder-32B-Instruct-GGUF:Q8_0",
    "family": "Qwen2.5-Coder-32B-Instruct",
    "name": "Qwen2.5-Coder-32B-Instruct",
    "task": "code",
    "params": 32,
    "quant": "Q8_0",
    "sizeBytes": 34820884672,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "Qwen/Qwen2.5-Coder-32B-Instruct-GGUF",
      "path": "qwen2.5-coder-32b-instruct-q8_0.gguf"
    }
  },
  {
    "id": "hf:Qwen/Qwen2.5-Coder-7B-Instruct-GGUF:Q2_K",
    "family": "Qwen2.5-Coder-7B-Instruct",
    "name": "Qwen2.5-Coder-7B-Instruct",
    "task": "code",
    "params": 7,
    "quant": "Q2_K",
    "sizeBytes": 3015940032,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "Qwen/Qwen2.5-Coder-7B-Instruct-GGUF",
      "path": "qwen2.5-coder-7b-instruct-q2_k.gguf"
    }
  },
  {
    "id": "hf:Qwen/Qwen2.5-Coder-7B-Instruct-GGUF:Q3_K_M",
    "family": "Qwen2.5-Coder-7B-Instruct",
    "name": "Qwen2.5-Coder-7B-Instruct",
    "task": "code",
    "params": 7,
    "quant": "Q3_K_M",
    "sizeBytes": 3808391104,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "Qwen/Qwen2.5-Coder-7B-Instruct-GGUF",
      "path": "qwen2.5-coder-7b-instruct-q3_k_m.gguf"
    }
  },
  {
    "id": "hf:Qwen/Qwen2.5-Coder-7B-Instruct-GGUF:Q4_0",
    "family": "Qwen2.5-Coder-7B-Instruct",
    "name": "Qwen2.5-Coder-7B-Instruct",
    "task": "code",
    "params": 7,
    "quant": "Q4_0",
    "sizeBytes": 4431390720,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "Qwen/Qwen2.5-Coder-7B-Instruct-GGUF",
      "path": "qwen2.5-coder-7b-instruct-q4_0.gguf"
    }
  },
  {
    "id": "hf:Qwen/Qwen2.5-Coder-7B-Instruct-GGUF:Q4_K_M",
    "family": "Qwen2.5-Coder-7B-Instruct",
    "name": "Qwen2.5-Coder-7B-Instruct",
    "task": "code",
    "params": 7,
    "quant": "Q4_K_M",
    "sizeBytes": 4683073536,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "Qwen/Qwen2.5-Coder-7B-Instruct-GGUF",
      "path": "qwen2.5-coder-7b-instruct-q4_k_m.gguf"
    }
  },
  {
    "id": "hf:Qwen/Qwen2.5-Coder-7B-Instruct-GGUF:Q5_0",
    "family": "Qwen2.5-Coder-7B-Instruct",
    "name": "Qwen2.5-Coder-7B-Instruct",
    "task": "code",
    "params": 7,
    "quant": "Q5_0",
    "sizeBytes": 5315176576,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "Qwen/Qwen2.5-Coder-7B-Instruct-GGUF",
      "path": "qwen2.5-coder-7b-instruct-q5_0.gguf"
    }
  },
  {
    "id": "hf:Qwen/Qwen2.5-Coder-7B-Instruct-GGUF:Q5_K_M",
    "family": "Qwen2.5-Coder-7B-Instruct",
    "name": "Qwen2.5-Coder-7B-Instruct",
    "task": "code",
    "params": 7,
    "quant": "Q5_K_M",
    "sizeBytes": 5444831232,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "Qwen/Qwen2.5-Coder-7B-Instruct-GGUF",
      "path": "qwen2.5-coder-7b-instruct-q5_k_m.gguf"
    }
  },
  {
    "id": "hf:Qwen/Qwen2.5-Coder-7B-Instruct-GGUF:Q6_K",
    "family": "Qwen2.5-Coder-7B-Instruct",
    "name": "Qwen2.5-Coder-7B-Instruct",
    "task": "code",
    "params": 7,
    "quant": "Q6_K",
    "sizeBytes": 6254198784,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "Qwen/Qwen2.5-Coder-7B-Instruct-GGUF",
      "path": "qwen2.5-coder-7b-instruct-q6_k.gguf"
    }
  },
  {
    "id": "hf:Qwen/Qwen2.5-Coder-7B-Instruct-GGUF:Q8_0",
    "family": "Qwen2.5-Coder-7B-Instruct",
    "name": "Qwen2.5-Coder-7B-Instruct",
    "task": "code",
    "params": 7,
    "quant": "Q8_0",
    "sizeBytes": 8098525184,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "Qwen/Qwen2.5-Coder-7B-Instruct-GGUF",
      "path": "qwen2.5-coder-7b-instruct-q8_0.gguf"
    }
  },
  {
    "id": "hf:bartowski/Llama-3.2-1B-Instruct-GGUF:IQ3_M",
    "family": "Llama-3.2-1B-Instruct",
    "name": "Llama-3.2-1B-Instruct",
    "task": "chat",
    "params": 1,
    "quant": "IQ3_M",
    "sizeBytes": 657289344,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "bartowski/Llama-3.2-1B-Instruct-GGUF",
      "path": "Llama-3.2-1B-Instruct-IQ3_M.gguf"
    }
  },
  {
    "id": "hf:bartowski/Llama-3.2-1B-Instruct-GGUF:IQ4_XS",
    "family": "Llama-3.2-1B-Instruct",
    "name": "Llama-3.2-1B-Instruct",
    "task": "chat",
    "params": 1,
    "quant": "IQ4_XS",
    "sizeBytes": 743141504,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "bartowski/Llama-3.2-1B-Instruct-GGUF",
      "path": "Llama-3.2-1B-Instruct-IQ4_XS.gguf"
    }
  },
  {
    "id": "hf:bartowski/Llama-3.2-1B-Instruct-GGUF:Q3_K_L",
    "family": "Llama-3.2-1B-Instruct",
    "name": "Llama-3.2-1B-Instruct",
    "task": "chat",
    "params": 1,
    "quant": "Q3_K_L",
    "sizeBytes": 732524672,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "bartowski/Llama-3.2-1B-Instruct-GGUF",
      "path": "Llama-3.2-1B-Instruct-Q3_K_L.gguf"
    }
  },
  {
    "id": "hf:bartowski/Llama-3.2-1B-Instruct-GGUF:Q3_K_XL",
    "family": "Llama-3.2-1B-Instruct",
    "name": "Llama-3.2-1B-Instruct",
    "task": "chat",
    "params": 1,
    "quant": "Q3_K_XL",
    "sizeBytes": 796139648,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "bartowski/Llama-3.2-1B-Instruct-GGUF",
      "path": "Llama-3.2-1B-Instruct-Q3_K_XL.gguf"
    }
  },
  {
    "id": "hf:bartowski/Llama-3.2-1B-Instruct-GGUF:Q4_0",
    "family": "Llama-3.2-1B-Instruct",
    "name": "Llama-3.2-1B-Instruct",
    "task": "chat",
    "params": 1,
    "quant": "Q4_0",
    "sizeBytes": 773025920,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "bartowski/Llama-3.2-1B-Instruct-GGUF",
      "path": "Llama-3.2-1B-Instruct-Q4_0.gguf"
    }
  },
  {
    "id": "hf:bartowski/Llama-3.2-1B-Instruct-GGUF:Q4_0_4_4",
    "family": "Llama-3.2-1B-Instruct",
    "name": "Llama-3.2-1B-Instruct",
    "task": "chat",
    "params": 1,
    "quant": "Q4_0_4_4",
    "sizeBytes": 770928768,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "bartowski/Llama-3.2-1B-Instruct-GGUF",
      "path": "Llama-3.2-1B-Instruct-Q4_0_4_4.gguf"
    }
  },
  {
    "id": "hf:bartowski/Llama-3.2-1B-Instruct-GGUF:Q4_0_4_8",
    "family": "Llama-3.2-1B-Instruct",
    "name": "Llama-3.2-1B-Instruct",
    "task": "chat",
    "params": 1,
    "quant": "Q4_0_4_8",
    "sizeBytes": 770928768,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "bartowski/Llama-3.2-1B-Instruct-GGUF",
      "path": "Llama-3.2-1B-Instruct-Q4_0_4_8.gguf"
    }
  },
  {
    "id": "hf:bartowski/Llama-3.2-1B-Instruct-GGUF:Q4_0_8_8",
    "family": "Llama-3.2-1B-Instruct",
    "name": "Llama-3.2-1B-Instruct",
    "task": "chat",
    "params": 1,
    "quant": "Q4_0_8_8",
    "sizeBytes": 770928768,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "bartowski/Llama-3.2-1B-Instruct-GGUF",
      "path": "Llama-3.2-1B-Instruct-Q4_0_8_8.gguf"
    }
  },
  {
    "id": "hf:bartowski/Llama-3.2-1B-Instruct-GGUF:Q4_K_L",
    "family": "Llama-3.2-1B-Instruct",
    "name": "Llama-3.2-1B-Instruct",
    "task": "chat",
    "params": 1,
    "quant": "Q4_K_L",
    "sizeBytes": 871309440,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "bartowski/Llama-3.2-1B-Instruct-GGUF",
      "path": "Llama-3.2-1B-Instruct-Q4_K_L.gguf"
    }
  },
  {
    "id": "hf:bartowski/Llama-3.2-1B-Instruct-GGUF:Q4_K_M",
    "family": "Llama-3.2-1B-Instruct",
    "name": "Llama-3.2-1B-Instruct",
    "task": "chat",
    "params": 1,
    "quant": "Q4_K_M",
    "sizeBytes": 807694464,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "bartowski/Llama-3.2-1B-Instruct-GGUF",
      "path": "Llama-3.2-1B-Instruct-Q4_K_M.gguf"
    }
  },
  {
    "id": "hf:bartowski/Llama-3.2-1B-Instruct-GGUF:Q4_K_S",
    "family": "Llama-3.2-1B-Instruct",
    "name": "Llama-3.2-1B-Instruct",
    "task": "chat",
    "params": 1,
    "quant": "Q4_K_S",
    "sizeBytes": 775647360,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "bartowski/Llama-3.2-1B-Instruct-GGUF",
      "path": "Llama-3.2-1B-Instruct-Q4_K_S.gguf"
    }
  },
  {
    "id": "hf:bartowski/Llama-3.2-1B-Instruct-GGUF:Q5_K_L",
    "family": "Llama-3.2-1B-Instruct",
    "name": "Llama-3.2-1B-Instruct",
    "task": "chat",
    "params": 1,
    "quant": "Q5_K_L",
    "sizeBytes": 975118464,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "bartowski/Llama-3.2-1B-Instruct-GGUF",
      "path": "Llama-3.2-1B-Instruct-Q5_K_L.gguf"
    }
  },
  {
    "id": "hf:bartowski/Llama-3.2-1B-Instruct-GGUF:Q5_K_M",
    "family": "Llama-3.2-1B-Instruct",
    "name": "Llama-3.2-1B-Instruct",
    "task": "chat",
    "params": 1,
    "quant": "Q5_K_M",
    "sizeBytes": 911503488,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "bartowski/Llama-3.2-1B-Instruct-GGUF",
      "path": "Llama-3.2-1B-Instruct-Q5_K_M.gguf"
    }
  },
  {
    "id": "hf:bartowski/Llama-3.2-1B-Instruct-GGUF:Q5_K_S",
    "family": "Llama-3.2-1B-Instruct",
    "name": "Llama-3.2-1B-Instruct",
    "task": "chat",
    "params": 1,
    "quant": "Q5_K_S",
    "sizeBytes": 892563584,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "bartowski/Llama-3.2-1B-Instruct-GGUF",
      "path": "Llama-3.2-1B-Instruct-Q5_K_S.gguf"
    }
  },
  {
    "id": "hf:bartowski/Llama-3.2-1B-Instruct-GGUF:Q6_K",
    "family": "Llama-3.2-1B-Instruct",
    "name": "Llama-3.2-1B-Instruct",
    "task": "chat",
    "params": 1,
    "quant": "Q6_K",
    "sizeBytes": 1021800576,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "bartowski/Llama-3.2-1B-Instruct-GGUF",
      "path": "Llama-3.2-1B-Instruct-Q6_K.gguf"
    }
  },
  {
    "id": "hf:bartowski/Llama-3.2-1B-Instruct-GGUF:Q6_K_L",
    "family": "Llama-3.2-1B-Instruct",
    "name": "Llama-3.2-1B-Instruct",
    "task": "chat",
    "params": 1,
    "quant": "Q6_K_L",
    "sizeBytes": 1085415552,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "bartowski/Llama-3.2-1B-Instruct-GGUF",
      "path": "Llama-3.2-1B-Instruct-Q6_K_L.gguf"
    }
  },
  {
    "id": "hf:bartowski/Llama-3.2-1B-Instruct-GGUF:Q8_0",
    "family": "Llama-3.2-1B-Instruct",
    "name": "Llama-3.2-1B-Instruct",
    "task": "chat",
    "params": 1,
    "quant": "Q8_0",
    "sizeBytes": 1321083008,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "bartowski/Llama-3.2-1B-Instruct-GGUF",
      "path": "Llama-3.2-1B-Instruct-Q8_0.gguf"
    }
  },
  {
    "id": "hf:bartowski/Meta-Llama-3.1-8B-Instruct-GGUF:IQ2_M",
    "family": "Meta-Llama-3.1-8B-Instruct",
    "name": "Meta-Llama-3.1-8B-Instruct",
    "task": "chat",
    "params": 8,
    "quant": "IQ2_M",
    "sizeBytes": 2948285856,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "bartowski/Meta-Llama-3.1-8B-Instruct-GGUF",
      "path": "Meta-Llama-3.1-8B-Instruct-IQ2_M.gguf"
    }
  },
  {
    "id": "hf:bartowski/Meta-Llama-3.1-8B-Instruct-GGUF:IQ3_M",
    "family": "Meta-Llama-3.1-8B-Instruct",
    "name": "Meta-Llama-3.1-8B-Instruct",
    "task": "chat",
    "params": 8,
    "quant": "IQ3_M",
    "sizeBytes": 3784828320,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "bartowski/Meta-Llama-3.1-8B-Instruct-GGUF",
      "path": "Meta-Llama-3.1-8B-Instruct-IQ3_M.gguf"
    }
  },
  {
    "id": "hf:bartowski/Meta-Llama-3.1-8B-Instruct-GGUF:IQ3_XS",
    "family": "Meta-Llama-3.1-8B-Instruct",
    "name": "Meta-Llama-3.1-8B-Instruct",
    "task": "chat",
    "params": 8,
    "quant": "IQ3_XS",
    "sizeBytes": 3518752160,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "bartowski/Meta-Llama-3.1-8B-Instruct-GGUF",
      "path": "Meta-Llama-3.1-8B-Instruct-IQ3_XS.gguf"
    }
  },
  {
    "id": "hf:bartowski/Meta-Llama-3.1-8B-Instruct-GGUF:IQ4_NL",
    "family": "Meta-Llama-3.1-8B-Instruct",
    "name": "Meta-Llama-3.1-8B-Instruct",
    "task": "chat",
    "params": 8,
    "quant": "IQ4_NL",
    "sizeBytes": 4677993888,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "bartowski/Meta-Llama-3.1-8B-Instruct-GGUF",
      "path": "Meta-Llama-3.1-8B-Instruct-IQ4_NL.gguf"
    }
  },
  {
    "id": "hf:bartowski/Meta-Llama-3.1-8B-Instruct-GGUF:IQ4_XS",
    "family": "Meta-Llama-3.1-8B-Instruct",
    "name": "Meta-Llama-3.1-8B-Instruct",
    "task": "chat",
    "params": 8,
    "quant": "IQ4_XS",
    "sizeBytes": 4447667616,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "bartowski/Meta-Llama-3.1-8B-Instruct-GGUF",
      "path": "Meta-Llama-3.1-8B-Instruct-IQ4_XS.gguf"
    }
  },
  {
    "id": "hf:bartowski/Meta-Llama-3.1-8B-Instruct-GGUF:Q2_K",
    "family": "Meta-Llama-3.1-8B-Instruct",
    "name": "Meta-Llama-3.1-8B-Instruct",
    "task": "chat",
    "params": 8,
    "quant": "Q2_K",
    "sizeBytes": 3179136416,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "bartowski/Meta-Llama-3.1-8B-Instruct-GGUF",
      "path": "Meta-Llama-3.1-8B-Instruct-Q2_K.gguf"
    }
  },
  {
    "id": "hf:bartowski/Meta-Llama-3.1-8B-Instruct-GGUF:Q2_K_L",
    "family": "Meta-Llama-3.1-8B-Instruct",
    "name": "Meta-Llama-3.1-8B-Instruct",
    "task": "chat",
    "params": 8,
    "quant": "Q2_K_L",
    "sizeBytes": 3692160416,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "bartowski/Meta-Llama-3.1-8B-Instruct-GGUF",
      "path": "Meta-Llama-3.1-8B-Instruct-Q2_K_L.gguf"
    }
  },
  {
    "id": "hf:bartowski/Meta-Llama-3.1-8B-Instruct-GGUF:Q3_K_L",
    "family": "Meta-Llama-3.1-8B-Instruct",
    "name": "Meta-Llama-3.1-8B-Instruct",
    "task": "chat",
    "params": 8,
    "quant": "Q3_K_L",
    "sizeBytes": 4321961376,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "bartowski/Meta-Llama-3.1-8B-Instruct-GGUF",
      "path": "Meta-Llama-3.1-8B-Instruct-Q3_K_L.gguf"
    }
  },
  {
    "id": "hf:bartowski/Meta-Llama-3.1-8B-Instruct-GGUF:Q3_K_M",
    "family": "Meta-Llama-3.1-8B-Instruct",
    "name": "Meta-Llama-3.1-8B-Instruct",
    "task": "chat",
    "params": 8,
    "quant": "Q3_K_M",
    "sizeBytes": 4018922912,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "bartowski/Meta-Llama-3.1-8B-Instruct-GGUF",
      "path": "Meta-Llama-3.1-8B-Instruct-Q3_K_M.gguf"
    }
  },
  {
    "id": "hf:bartowski/Meta-Llama-3.1-8B-Instruct-GGUF:Q3_K_S",
    "family": "Meta-Llama-3.1-8B-Instruct",
    "name": "Meta-Llama-3.1-8B-Instruct",
    "task": "chat",
    "params": 8,
    "quant": "Q3_K_S",
    "sizeBytes": 3664504224,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "bartowski/Meta-Llama-3.1-8B-Instruct-GGUF",
      "path": "Meta-Llama-3.1-8B-Instruct-Q3_K_S.gguf"
    }
  },
  {
    "id": "hf:bartowski/Meta-Llama-3.1-8B-Instruct-GGUF:Q3_K_XL",
    "family": "Meta-Llama-3.1-8B-Instruct",
    "name": "Meta-Llama-3.1-8B-Instruct",
    "task": "chat",
    "params": 8,
    "quant": "Q3_K_XL",
    "sizeBytes": 4781630880,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "bartowski/Meta-Llama-3.1-8B-Instruct-GGUF",
      "path": "Meta-Llama-3.1-8B-Instruct-Q3_K_XL.gguf"
    }
  },
  {
    "id": "hf:bartowski/Meta-Llama-3.1-8B-Instruct-GGUF:Q4_0_4_4",
    "family": "Meta-Llama-3.1-8B-Instruct",
    "name": "Meta-Llama-3.1-8B-Instruct",
    "task": "chat",
    "params": 8,
    "quant": "Q4_0_4_4",
    "sizeBytes": 4661216672,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "bartowski/Meta-Llama-3.1-8B-Instruct-GGUF",
      "path": "Meta-Llama-3.1-8B-Instruct-Q4_0_4_4.gguf"
    }
  },
  {
    "id": "hf:bartowski/Meta-Llama-3.1-8B-Instruct-GGUF:Q4_0_4_8",
    "family": "Meta-Llama-3.1-8B-Instruct",
    "name": "Meta-Llama-3.1-8B-Instruct",
    "task": "chat",
    "params": 8,
    "quant": "Q4_0_4_8",
    "sizeBytes": 4661216672,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "bartowski/Meta-Llama-3.1-8B-Instruct-GGUF",
      "path": "Meta-Llama-3.1-8B-Instruct-Q4_0_4_8.gguf"
    }
  },
  {
    "id": "hf:bartowski/Meta-Llama-3.1-8B-Instruct-GGUF:Q4_0_8_8",
    "family": "Meta-Llama-3.1-8B-Instruct",
    "name": "Meta-Llama-3.1-8B-Instruct",
    "task": "chat",
    "params": 8,
    "quant": "Q4_0_8_8",
    "sizeBytes": 4661216672,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "bartowski/Meta-Llama-3.1-8B-Instruct-GGUF",
      "path": "Meta-Llama-3.1-8B-Instruct-Q4_0_8_8.gguf"
    }
  },
  {
    "id": "hf:bartowski/Meta-Llama-3.1-8B-Instruct-GGUF:Q4_K_L",
    "family": "Meta-Llama-3.1-8B-Instruct",
    "name": "Meta-Llama-3.1-8B-Instruct",
    "task": "chat",
    "params": 8,
    "quant": "Q4_K_L",
    "sizeBytes": 5310637472,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "bartowski/Meta-Llama-3.1-8B-Instruct-GGUF",
      "path": "Meta-Llama-3.1-8B-Instruct-Q4_K_L.gguf"
    }
  },
  {
    "id": "hf:bartowski/Meta-Llama-3.1-8B-Instruct-GGUF:Q4_K_M",
    "family": "Meta-Llama-3.1-8B-Instruct",
    "name": "Meta-Llama-3.1-8B-Instruct",
    "task": "chat",
    "params": 8,
    "quant": "Q4_K_M",
    "sizeBytes": 4920739232,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "bartowski/Meta-Llama-3.1-8B-Instruct-GGUF",
      "path": "Meta-Llama-3.1-8B-Instruct-Q4_K_M.gguf"
    }
  },
  {
    "id": "hf:bartowski/Meta-Llama-3.1-8B-Instruct-GGUF:Q4_K_S",
    "family": "Meta-Llama-3.1-8B-Instruct",
    "name": "Meta-Llama-3.1-8B-Instruct",
    "task": "chat",
    "params": 8,
    "quant": "Q4_K_S",
    "sizeBytes": 4692673952,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "bartowski/Meta-Llama-3.1-8B-Instruct-GGUF",
      "path": "Meta-Llama-3.1-8B-Instruct-Q4_K_S.gguf"
    }
  },
  {
    "id": "hf:bartowski/Meta-Llama-3.1-8B-Instruct-GGUF:Q5_K_L",
    "family": "Meta-Llama-3.1-8B-Instruct",
    "name": "Meta-Llama-3.1-8B-Instruct",
    "task": "chat",
    "params": 8,
    "quant": "Q5_K_L",
    "sizeBytes": 6057223584,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "bartowski/Meta-Llama-3.1-8B-Instruct-GGUF",
      "path": "Meta-Llama-3.1-8B-Instruct-Q5_K_L.gguf"
    }
  },
  {
    "id": "hf:bartowski/Meta-Llama-3.1-8B-Instruct-GGUF:Q5_K_M",
    "family": "Meta-Llama-3.1-8B-Instruct",
    "name": "Meta-Llama-3.1-8B-Instruct",
    "task": "chat",
    "params": 8,
    "quant": "Q5_K_M",
    "sizeBytes": 5732992416,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "bartowski/Meta-Llama-3.1-8B-Instruct-GGUF",
      "path": "Meta-Llama-3.1-8B-Instruct-Q5_K_M.gguf"
    }
  },
  {
    "id": "hf:bartowski/Meta-Llama-3.1-8B-Instruct-GGUF:Q5_K_S",
    "family": "Meta-Llama-3.1-8B-Instruct",
    "name": "Meta-Llama-3.1-8B-Instruct",
    "task": "chat",
    "params": 8,
    "quant": "Q5_K_S",
    "sizeBytes": 5599298976,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "bartowski/Meta-Llama-3.1-8B-Instruct-GGUF",
      "path": "Meta-Llama-3.1-8B-Instruct-Q5_K_S.gguf"
    }
  },
  {
    "id": "hf:bartowski/Meta-Llama-3.1-8B-Instruct-GGUF:Q6_K",
    "family": "Meta-Llama-3.1-8B-Instruct",
    "name": "Meta-Llama-3.1-8B-Instruct",
    "task": "chat",
    "params": 8,
    "quant": "Q6_K",
    "sizeBytes": 6596011424,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "bartowski/Meta-Llama-3.1-8B-Instruct-GGUF",
      "path": "Meta-Llama-3.1-8B-Instruct-Q6_K.gguf"
    }
  },
  {
    "id": "hf:bartowski/Meta-Llama-3.1-8B-Instruct-GGUF:Q6_K_L",
    "family": "Meta-Llama-3.1-8B-Instruct",
    "name": "Meta-Llama-3.1-8B-Instruct",
    "task": "chat",
    "params": 8,
    "quant": "Q6_K_L",
    "sizeBytes": 6850471328,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "bartowski/Meta-Llama-3.1-8B-Instruct-GGUF",
      "path": "Meta-Llama-3.1-8B-Instruct-Q6_K_L.gguf"
    }
  },
  {
    "id": "hf:bartowski/Meta-Llama-3.1-8B-Instruct-GGUF:Q8_0",
    "family": "Meta-Llama-3.1-8B-Instruct",
    "name": "Meta-Llama-3.1-8B-Instruct",
    "task": "chat",
    "params": 8,
    "quant": "Q8_0",
    "sizeBytes": 8540775840,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "bartowski/Meta-Llama-3.1-8B-Instruct-GGUF",
      "path": "Meta-Llama-3.1-8B-Instruct-Q8_0.gguf"
    }
  },
  {
    "id": "hf:hesamation/Qwen3.6-35B-A3B-Claude-4.6-Opus-Reasoning-Distilled-GGUF:Q4_K_M",
    "family": "Qwen3.6-35B-A3B-Claude-4.6-Opus-Reasoning-Distilled",
    "name": "Qwen3.6-35B-A3B-Claude-4.6-Opus-Reasoning-Distilled",
    "task": "reasoning",
    "params": 35,
    "quant": "Q4_K_M",
    "sizeBytes": 21166759104,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "hesamation/Qwen3.6-35B-A3B-Claude-4.6-Opus-Reasoning-Distilled-GGUF",
      "path": "Qwen3.6-35B-A3B-Claude-4.6-Opus-Reasoning-Distilled.Q4_K_M.gguf"
    }
  },
  {
    "id": "hf:hesamation/Qwen3.6-35B-A3B-Claude-4.6-Opus-Reasoning-Distilled-GGUF:Q5_K_M",
    "family": "Qwen3.6-35B-A3B-Claude-4.6-Opus-Reasoning-Distilled",
    "name": "Qwen3.6-35B-A3B-Claude-4.6-Opus-Reasoning-Distilled",
    "task": "reasoning",
    "params": 35,
    "quant": "Q5_K_M",
    "sizeBytes": 24729132224,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "hesamation/Qwen3.6-35B-A3B-Claude-4.6-Opus-Reasoning-Distilled-GGUF",
      "path": "Qwen3.6-35B-A3B-Claude-4.6-Opus-Reasoning-Distilled.Q5_K_M.gguf"
    }
  },
  {
    "id": "hf:hesamation/Qwen3.6-35B-A3B-Claude-4.6-Opus-Reasoning-Distilled-GGUF:Q6_K",
    "family": "Qwen3.6-35B-A3B-Claude-4.6-Opus-Reasoning-Distilled",
    "name": "Qwen3.6-35B-A3B-Claude-4.6-Opus-Reasoning-Distilled",
    "task": "reasoning",
    "params": 35,
    "quant": "Q6_K",
    "sizeBytes": 28514153664,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "hesamation/Qwen3.6-35B-A3B-Claude-4.6-Opus-Reasoning-Distilled-GGUF",
      "path": "Qwen3.6-35B-A3B-Claude-4.6-Opus-Reasoning-Distilled.Q6_K.gguf"
    }
  },
  {
    "id": "hf:hesamation/Qwen3.6-35B-A3B-Claude-4.6-Opus-Reasoning-Distilled-GGUF:Q8_0",
    "family": "Qwen3.6-35B-A3B-Claude-4.6-Opus-Reasoning-Distilled",
    "name": "Qwen3.6-35B-A3B-Claude-4.6-Opus-Reasoning-Distilled",
    "task": "reasoning",
    "params": 35,
    "quant": "Q8_0",
    "sizeBytes": 36903140544,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "hesamation/Qwen3.6-35B-A3B-Claude-4.6-Opus-Reasoning-Distilled-GGUF",
      "path": "Qwen3.6-35B-A3B-Claude-4.6-Opus-Reasoning-Distilled.Q8_0.gguf"
    }
  },
  {
    "id": "hf:hugging-quants/Llama-3.2-1B-Instruct-Q8_0-GGUF:Q8_0",
    "family": "Llama-3.2-1B-Instruct-Q8_0",
    "name": "Llama-3.2-1B-Instruct-Q8_0",
    "task": "chat",
    "params": 1,
    "quant": "Q8_0",
    "sizeBytes": 1321079200,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "hugging-quants/Llama-3.2-1B-Instruct-Q8_0-GGUF",
      "path": "llama-3.2-1b-instruct-q8_0.gguf"
    }
  },
  {
    "id": "hf:unsloth/Qwen3-Coder-30B-A3B-Instruct-GGUF:IQ1_M",
    "family": "Qwen3-Coder-30B-A3B-Instruct",
    "name": "Qwen3-Coder-30B-A3B-Instruct",
    "task": "code",
    "params": 30,
    "quant": "IQ1_M",
    "sizeBytes": 9627540640,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "unsloth/Qwen3-Coder-30B-A3B-Instruct-GGUF",
      "path": "Qwen3-Coder-30B-A3B-Instruct-UD-IQ1_M.gguf"
    }
  },
  {
    "id": "hf:unsloth/Qwen3-Coder-30B-A3B-Instruct-GGUF:IQ1_S",
    "family": "Qwen3-Coder-30B-A3B-Instruct",
    "name": "Qwen3-Coder-30B-A3B-Instruct",
    "task": "code",
    "params": 30,
    "quant": "IQ1_S",
    "sizeBytes": 8914328736,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "unsloth/Qwen3-Coder-30B-A3B-Instruct-GGUF",
      "path": "Qwen3-Coder-30B-A3B-Instruct-UD-IQ1_S.gguf"
    }
  },
  {
    "id": "hf:unsloth/Qwen3-Coder-30B-A3B-Instruct-GGUF:IQ2_M",
    "family": "Qwen3-Coder-30B-A3B-Instruct",
    "name": "Qwen3-Coder-30B-A3B-Instruct",
    "task": "code",
    "params": 30,
    "quant": "IQ2_M",
    "sizeBytes": 10837007520,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "unsloth/Qwen3-Coder-30B-A3B-Instruct-GGUF",
      "path": "Qwen3-Coder-30B-A3B-Instruct-UD-IQ2_M.gguf"
    }
  },
  {
    "id": "hf:unsloth/Qwen3-Coder-30B-A3B-Instruct-GGUF:IQ2_XXS",
    "family": "Qwen3-Coder-30B-A3B-Instruct",
    "name": "Qwen3-Coder-30B-A3B-Instruct",
    "task": "code",
    "params": 30,
    "quant": "IQ2_XXS",
    "sizeBytes": 10333691040,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "unsloth/Qwen3-Coder-30B-A3B-Instruct-GGUF",
      "path": "Qwen3-Coder-30B-A3B-Instruct-UD-IQ2_XXS.gguf"
    }
  },
  {
    "id": "hf:unsloth/Qwen3-Coder-30B-A3B-Instruct-GGUF:IQ3_XXS",
    "family": "Qwen3-Coder-30B-A3B-Instruct",
    "name": "Qwen3-Coder-30B-A3B-Instruct",
    "task": "code",
    "params": 30,
    "quant": "IQ3_XXS",
    "sizeBytes": 12848766112,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "unsloth/Qwen3-Coder-30B-A3B-Instruct-GGUF",
      "path": "Qwen3-Coder-30B-A3B-Instruct-UD-IQ3_XXS.gguf"
    }
  },
  {
    "id": "hf:unsloth/Qwen3-Coder-30B-A3B-Instruct-GGUF:IQ4_NL",
    "family": "Qwen3-Coder-30B-A3B-Instruct",
    "name": "Qwen3-Coder-30B-A3B-Instruct",
    "task": "code",
    "params": 30,
    "quant": "IQ4_NL",
    "sizeBytes": 17310784672,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "unsloth/Qwen3-Coder-30B-A3B-Instruct-GGUF",
      "path": "Qwen3-Coder-30B-A3B-Instruct-IQ4_NL.gguf"
    }
  },
  {
    "id": "hf:unsloth/Qwen3-Coder-30B-A3B-Instruct-GGUF:IQ4_XS",
    "family": "Qwen3-Coder-30B-A3B-Instruct",
    "name": "Qwen3-Coder-30B-A3B-Instruct",
    "task": "code",
    "params": 30,
    "quant": "IQ4_XS",
    "sizeBytes": 16378076320,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "unsloth/Qwen3-Coder-30B-A3B-Instruct-GGUF",
      "path": "Qwen3-Coder-30B-A3B-Instruct-IQ4_XS.gguf"
    }
  },
  {
    "id": "hf:unsloth/Qwen3-Coder-30B-A3B-Instruct-GGUF:Q2_K",
    "family": "Qwen3-Coder-30B-A3B-Instruct",
    "name": "Qwen3-Coder-30B-A3B-Instruct",
    "task": "code",
    "params": 30,
    "quant": "Q2_K",
    "sizeBytes": 11258612896,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "unsloth/Qwen3-Coder-30B-A3B-Instruct-GGUF",
      "path": "Qwen3-Coder-30B-A3B-Instruct-Q2_K.gguf"
    }
  },
  {
    "id": "hf:unsloth/Qwen3-Coder-30B-A3B-Instruct-GGUF:Q2_K_L",
    "family": "Qwen3-Coder-30B-A3B-Instruct",
    "name": "Qwen3-Coder-30B-A3B-Instruct",
    "task": "code",
    "params": 30,
    "quant": "Q2_K_L",
    "sizeBytes": 11331542176,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "unsloth/Qwen3-Coder-30B-A3B-Instruct-GGUF",
      "path": "Qwen3-Coder-30B-A3B-Instruct-Q2_K_L.gguf"
    }
  },
  {
    "id": "hf:unsloth/Qwen3-Coder-30B-A3B-Instruct-GGUF:Q2_K_XL",
    "family": "Qwen3-Coder-30B-A3B-Instruct",
    "name": "Qwen3-Coder-30B-A3B-Instruct",
    "task": "code",
    "params": 30,
    "quant": "Q2_K_XL",
    "sizeBytes": 11788590240,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "unsloth/Qwen3-Coder-30B-A3B-Instruct-GGUF",
      "path": "Qwen3-Coder-30B-A3B-Instruct-UD-Q2_K_XL.gguf"
    }
  },
  {
    "id": "hf:unsloth/Qwen3-Coder-30B-A3B-Instruct-GGUF:Q3_K_M",
    "family": "Qwen3-Coder-30B-A3B-Instruct",
    "name": "Qwen3-Coder-30B-A3B-Instruct",
    "task": "code",
    "params": 30,
    "quant": "Q3_K_M",
    "sizeBytes": 14711850144,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "unsloth/Qwen3-Coder-30B-A3B-Instruct-GGUF",
      "path": "Qwen3-Coder-30B-A3B-Instruct-Q3_K_M.gguf"
    }
  },
  {
    "id": "hf:unsloth/Qwen3-Coder-30B-A3B-Instruct-GGUF:Q3_K_S",
    "family": "Qwen3-Coder-30B-A3B-Instruct",
    "name": "Qwen3-Coder-30B-A3B-Instruct",
    "task": "code",
    "params": 30,
    "quant": "Q3_K_S",
    "sizeBytes": 13292471456,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "unsloth/Qwen3-Coder-30B-A3B-Instruct-GGUF",
      "path": "Qwen3-Coder-30B-A3B-Instruct-Q3_K_S.gguf"
    }
  },
  {
    "id": "hf:unsloth/Qwen3-Coder-30B-A3B-Instruct-GGUF:Q3_K_XL",
    "family": "Qwen3-Coder-30B-A3B-Instruct",
    "name": "Qwen3-Coder-30B-A3B-Instruct",
    "task": "code",
    "params": 30,
    "quant": "Q3_K_XL",
    "sizeBytes": 13806312608,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "unsloth/Qwen3-Coder-30B-A3B-Instruct-GGUF",
      "path": "Qwen3-Coder-30B-A3B-Instruct-UD-Q3_K_XL.gguf"
    }
  },
  {
    "id": "hf:unsloth/Qwen3-Coder-30B-A3B-Instruct-GGUF:Q4_0",
    "family": "Qwen3-Coder-30B-A3B-Instruct",
    "name": "Qwen3-Coder-30B-A3B-Instruct",
    "task": "code",
    "params": 30,
    "quant": "Q4_0",
    "sizeBytes": 17379990688,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "unsloth/Qwen3-Coder-30B-A3B-Instruct-GGUF",
      "path": "Qwen3-Coder-30B-A3B-Instruct-Q4_0.gguf"
    }
  },
  {
    "id": "hf:unsloth/Qwen3-Coder-30B-A3B-Instruct-GGUF:Q4_1",
    "family": "Qwen3-Coder-30B-A3B-Instruct",
    "name": "Qwen3-Coder-30B-A3B-Instruct",
    "task": "code",
    "params": 30,
    "quant": "Q4_1",
    "sizeBytes": 19192503456,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "unsloth/Qwen3-Coder-30B-A3B-Instruct-GGUF",
      "path": "Qwen3-Coder-30B-A3B-Instruct-Q4_1.gguf"
    }
  },
  {
    "id": "hf:unsloth/Qwen3-Coder-30B-A3B-Instruct-GGUF:Q4_K_M",
    "family": "Qwen3-Coder-30B-A3B-Instruct",
    "name": "Qwen3-Coder-30B-A3B-Instruct",
    "task": "code",
    "params": 30,
    "quant": "Q4_K_M",
    "sizeBytes": 18556689568,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "unsloth/Qwen3-Coder-30B-A3B-Instruct-GGUF",
      "path": "Qwen3-Coder-30B-A3B-Instruct-Q4_K_M.gguf"
    }
  },
  {
    "id": "hf:unsloth/Qwen3-Coder-30B-A3B-Instruct-GGUF:Q4_K_S",
    "family": "Qwen3-Coder-30B-A3B-Instruct",
    "name": "Qwen3-Coder-30B-A3B-Instruct",
    "task": "code",
    "params": 30,
    "quant": "Q4_K_S",
    "sizeBytes": 17456012448,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "unsloth/Qwen3-Coder-30B-A3B-Instruct-GGUF",
      "path": "Qwen3-Coder-30B-A3B-Instruct-Q4_K_S.gguf"
    }
  },
  {
    "id": "hf:unsloth/Qwen3-Coder-30B-A3B-Instruct-GGUF:Q4_K_XL",
    "family": "Qwen3-Coder-30B-A3B-Instruct",
    "name": "Qwen3-Coder-30B-A3B-Instruct",
    "task": "code",
    "params": 30,
    "quant": "Q4_K_XL",
    "sizeBytes": 17665334432,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "unsloth/Qwen3-Coder-30B-A3B-Instruct-GGUF",
      "path": "Qwen3-Coder-30B-A3B-Instruct-UD-Q4_K_XL.gguf"
    }
  },
  {
    "id": "hf:unsloth/Qwen3-Coder-30B-A3B-Instruct-GGUF:Q5_K_M",
    "family": "Qwen3-Coder-30B-A3B-Instruct",
    "name": "Qwen3-Coder-30B-A3B-Instruct",
    "task": "code",
    "params": 30,
    "quant": "Q5_K_M",
    "sizeBytes": 21725584544,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "unsloth/Qwen3-Coder-30B-A3B-Instruct-GGUF",
      "path": "Qwen3-Coder-30B-A3B-Instruct-Q5_K_M.gguf"
    }
  },
  {
    "id": "hf:unsloth/Qwen3-Coder-30B-A3B-Instruct-GGUF:Q5_K_S",
    "family": "Qwen3-Coder-30B-A3B-Instruct",
    "name": "Qwen3-Coder-30B-A3B-Instruct",
    "task": "code",
    "params": 30,
    "quant": "Q5_K_S",
    "sizeBytes": 21080513696,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "unsloth/Qwen3-Coder-30B-A3B-Instruct-GGUF",
      "path": "Qwen3-Coder-30B-A3B-Instruct-Q5_K_S.gguf"
    }
  },
  {
    "id": "hf:unsloth/Qwen3-Coder-30B-A3B-Instruct-GGUF:Q5_K_XL",
    "family": "Qwen3-Coder-30B-A3B-Instruct",
    "name": "Qwen3-Coder-30B-A3B-Instruct",
    "task": "code",
    "params": 30,
    "quant": "Q5_K_XL",
    "sizeBytes": 21740305568,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "unsloth/Qwen3-Coder-30B-A3B-Instruct-GGUF",
      "path": "Qwen3-Coder-30B-A3B-Instruct-UD-Q5_K_XL.gguf"
    }
  },
  {
    "id": "hf:unsloth/Qwen3-Coder-30B-A3B-Instruct-GGUF:Q6_K",
    "family": "Qwen3-Coder-30B-A3B-Instruct",
    "name": "Qwen3-Coder-30B-A3B-Instruct",
    "task": "code",
    "params": 30,
    "quant": "Q6_K",
    "sizeBytes": 25092535456,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "unsloth/Qwen3-Coder-30B-A3B-Instruct-GGUF",
      "path": "Qwen3-Coder-30B-A3B-Instruct-Q6_K.gguf"
    }
  },
  {
    "id": "hf:unsloth/Qwen3-Coder-30B-A3B-Instruct-GGUF:Q6_K_XL",
    "family": "Qwen3-Coder-30B-A3B-Instruct",
    "name": "Qwen3-Coder-30B-A3B-Instruct",
    "task": "code",
    "params": 30,
    "quant": "Q6_K_XL",
    "sizeBytes": 26340328608,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "unsloth/Qwen3-Coder-30B-A3B-Instruct-GGUF",
      "path": "Qwen3-Coder-30B-A3B-Instruct-UD-Q6_K_XL.gguf"
    }
  },
  {
    "id": "hf:unsloth/Qwen3-Coder-30B-A3B-Instruct-GGUF:Q8_0",
    "family": "Qwen3-Coder-30B-A3B-Instruct",
    "name": "Qwen3-Coder-30B-A3B-Instruct",
    "task": "code",
    "params": 30,
    "quant": "Q8_0",
    "sizeBytes": 32483935392,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "unsloth/Qwen3-Coder-30B-A3B-Instruct-GGUF",
      "path": "Qwen3-Coder-30B-A3B-Instruct-Q8_0.gguf"
    }
  },
  {
    "id": "hf:unsloth/Qwen3-Coder-30B-A3B-Instruct-GGUF:Q8_K_XL",
    "family": "Qwen3-Coder-30B-A3B-Instruct",
    "name": "Qwen3-Coder-30B-A3B-Instruct",
    "task": "code",
    "params": 30,
    "quant": "Q8_K_XL",
    "sizeBytes": 35989947552,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "unsloth/Qwen3-Coder-30B-A3B-Instruct-GGUF",
      "path": "Qwen3-Coder-30B-A3B-Instruct-UD-Q8_K_XL.gguf"
    }
  },
  {
    "id": "hf:unsloth/Qwen3-Coder-Next-GGUF:IQ1_M",
    "family": "Qwen3-Coder-Next",
    "name": "Qwen3-Coder-Next",
    "task": "code",
    "quant": "IQ1_M",
    "sizeBytes": 21701693440,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "unsloth/Qwen3-Coder-Next-GGUF",
      "path": "Qwen3-Coder-Next-UD-IQ1_M.gguf"
    }
  },
  {
    "id": "hf:unsloth/Qwen3-Coder-Next-GGUF:IQ1_S",
    "family": "Qwen3-Coder-Next",
    "name": "Qwen3-Coder-Next",
    "task": "code",
    "quant": "IQ1_S",
    "sizeBytes": 21508749344,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "unsloth/Qwen3-Coder-Next-GGUF",
      "path": "Qwen3-Coder-Next-UD-IQ1_S.gguf"
    }
  },
  {
    "id": "hf:unsloth/Qwen3-Coder-Next-GGUF:IQ2_M",
    "family": "Qwen3-Coder-Next",
    "name": "Qwen3-Coder-Next",
    "task": "code",
    "quant": "IQ2_M",
    "sizeBytes": 24962293760,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "unsloth/Qwen3-Coder-Next-GGUF",
      "path": "Qwen3-Coder-Next-UD-IQ2_M.gguf"
    }
  },
  {
    "id": "hf:unsloth/Qwen3-Coder-Next-GGUF:IQ2_XXS",
    "family": "Qwen3-Coder-Next",
    "name": "Qwen3-Coder-Next",
    "task": "code",
    "quant": "IQ2_XXS",
    "sizeBytes": 23312490496,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "unsloth/Qwen3-Coder-Next-GGUF",
      "path": "Qwen3-Coder-Next-UD-IQ2_XXS.gguf"
    }
  },
  {
    "id": "hf:unsloth/Qwen3-Coder-Next-GGUF:IQ3_S",
    "family": "Qwen3-Coder-Next",
    "name": "Qwen3-Coder-Next",
    "task": "code",
    "quant": "IQ3_S",
    "sizeBytes": 29690687488,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "unsloth/Qwen3-Coder-Next-GGUF",
      "path": "Qwen3-Coder-Next-UD-IQ3_S.gguf"
    }
  },
  {
    "id": "hf:unsloth/Qwen3-Coder-Next-GGUF:IQ3_XXS",
    "family": "Qwen3-Coder-Next",
    "name": "Qwen3-Coder-Next",
    "task": "code",
    "quant": "IQ3_XXS",
    "sizeBytes": 28482506752,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "unsloth/Qwen3-Coder-Next-GGUF",
      "path": "Qwen3-Coder-Next-UD-IQ3_XXS.gguf"
    }
  },
  {
    "id": "hf:unsloth/Qwen3-Coder-Next-GGUF:IQ4_NL",
    "family": "Qwen3-Coder-Next",
    "name": "Qwen3-Coder-Next",
    "task": "code",
    "quant": "IQ4_NL",
    "sizeBytes": 45130344480,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "unsloth/Qwen3-Coder-Next-GGUF",
      "path": "Qwen3-Coder-Next-IQ4_NL.gguf"
    }
  },
  {
    "id": "hf:unsloth/Qwen3-Coder-Next-GGUF:IQ4_XS",
    "family": "Qwen3-Coder-Next",
    "name": "Qwen3-Coder-Next",
    "task": "code",
    "quant": "IQ4_XS",
    "sizeBytes": 42676135968,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "unsloth/Qwen3-Coder-Next-GGUF",
      "path": "Qwen3-Coder-Next-IQ4_XS.gguf"
    }
  },
  {
    "id": "hf:unsloth/Qwen3-Coder-Next-GGUF:Q2_K",
    "family": "Qwen3-Coder-Next",
    "name": "Qwen3-Coder-Next",
    "task": "code",
    "quant": "Q2_K",
    "sizeBytes": 29224450080,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "unsloth/Qwen3-Coder-Next-GGUF",
      "path": "Qwen3-Coder-Next-Q2_K.gguf"
    }
  },
  {
    "id": "hf:unsloth/Qwen3-Coder-Next-GGUF:Q2_K_L",
    "family": "Qwen3-Coder-Next",
    "name": "Qwen3-Coder-Next",
    "task": "code",
    "quant": "Q2_K_L",
    "sizeBytes": 29297379360,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "unsloth/Qwen3-Coder-Next-GGUF",
      "path": "Qwen3-Coder-Next-Q2_K_L.gguf"
    }
  },
  {
    "id": "hf:unsloth/Qwen3-Coder-Next-GGUF:Q2_K_XL",
    "family": "Qwen3-Coder-Next",
    "name": "Qwen3-Coder-Next",
    "task": "code",
    "quant": "Q2_K_XL",
    "sizeBytes": 26760515584,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "unsloth/Qwen3-Coder-Next-GGUF",
      "path": "Qwen3-Coder-Next-UD-Q2_K_XL.gguf"
    }
  },
  {
    "id": "hf:unsloth/Qwen3-Coder-Next-GGUF:Q3_K_M",
    "family": "Qwen3-Coder-Next",
    "name": "Qwen3-Coder-Next",
    "task": "code",
    "quant": "Q3_K_M",
    "sizeBytes": 38322487328,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "unsloth/Qwen3-Coder-Next-GGUF",
      "path": "Qwen3-Coder-Next-Q3_K_M.gguf"
    }
  },
  {
    "id": "hf:unsloth/Qwen3-Coder-Next-GGUF:Q3_K_S",
    "family": "Qwen3-Coder-Next",
    "name": "Qwen3-Coder-Next",
    "task": "code",
    "quant": "Q3_K_S",
    "sizeBytes": 34603089952,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "unsloth/Qwen3-Coder-Next-GGUF",
      "path": "Qwen3-Coder-Next-Q3_K_S.gguf"
    }
  },
  {
    "id": "hf:unsloth/Qwen3-Coder-Next-GGUF:Q3_K_XL",
    "family": "Qwen3-Coder-Next",
    "name": "Qwen3-Coder-Next",
    "task": "code",
    "quant": "Q3_K_XL",
    "sizeBytes": 36282685440,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "unsloth/Qwen3-Coder-Next-GGUF",
      "path": "Qwen3-Coder-Next-UD-Q3_K_XL.gguf"
    }
  },
  {
    "id": "hf:unsloth/Qwen3-Coder-Next-GGUF:Q4_0",
    "family": "Qwen3-Coder-Next",
    "name": "Qwen3-Coder-Next",
    "task": "code",
    "quant": "Q4_0",
    "sizeBytes": 45330098208,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "unsloth/Qwen3-Coder-Next-GGUF",
      "path": "Qwen3-Coder-Next-Q4_0.gguf"
    }
  },
  {
    "id": "hf:unsloth/Qwen3-Coder-Next-GGUF:Q4_1",
    "family": "Qwen3-Coder-Next",
    "name": "Qwen3-Coder-Next",
    "task": "code",
    "quant": "Q4_1",
    "sizeBytes": 50057423200,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "unsloth/Qwen3-Coder-Next-GGUF",
      "path": "Q4_1/Qwen3-Coder-Next-Q4_1.gguf"
    }
  },
  {
    "id": "hf:unsloth/Qwen3-Coder-Next-GGUF:Q4_K_M",
    "family": "Qwen3-Coder-Next",
    "name": "Qwen3-Coder-Next",
    "task": "code",
    "quant": "Q4_K_M",
    "sizeBytes": 48528320544,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "unsloth/Qwen3-Coder-Next-GGUF",
      "path": "Qwen3-Coder-Next-Q4_K_M.gguf"
    }
  },
  {
    "id": "hf:unsloth/Qwen3-Coder-Next-GGUF:Q4_K_S",
    "family": "Qwen3-Coder-Next",
    "name": "Qwen3-Coder-Next",
    "task": "code",
    "quant": "Q4_K_S",
    "sizeBytes": 45531949088,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "unsloth/Qwen3-Coder-Next-GGUF",
      "path": "Qwen3-Coder-Next-Q4_K_S.gguf"
    }
  },
  {
    "id": "hf:unsloth/Qwen3-Coder-Next-GGUF:Q4_K_XL",
    "family": "Qwen3-Coder-Next",
    "name": "Qwen3-Coder-Next",
    "task": "code",
    "quant": "Q4_K_XL",
    "sizeBytes": 49608478720,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "unsloth/Qwen3-Coder-Next-GGUF",
      "path": "Qwen3-Coder-Next-UD-Q4_K_XL.gguf"
    }
  },
  {
    "id": "hf:unsloth/Qwen3-Coder-Next-GGUF:Q5_K_M",
    "family": "Qwen3-Coder-Next",
    "name": "Qwen3-Coder-Next",
    "task": "code",
    "quant": "Q5_K_M",
    "sizeBytes": 56847886688,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "unsloth/Qwen3-Coder-Next-GGUF",
      "path": "Q5_K_M/Qwen3-Coder-Next-Q5_K_M.gguf"
    }
  },
  {
    "id": "hf:unsloth/Qwen3-Coder-Next-GGUF:Q5_K_S",
    "family": "Qwen3-Coder-Next",
    "name": "Qwen3-Coder-Next",
    "task": "code",
    "quant": "Q5_K_S",
    "sizeBytes": 55055280480,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "unsloth/Qwen3-Coder-Next-GGUF",
      "path": "Q5_K_S/Qwen3-Coder-Next-Q5_K_S.gguf"
    }
  },
  {
    "id": "hf:unsloth/Qwen3-Coder-Next-GGUF:Q5_K_XL",
    "family": "Qwen3-Coder-Next",
    "name": "Qwen3-Coder-Next",
    "task": "code",
    "quant": "Q5_K_XL",
    "sizeBytes": 59541180768,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "unsloth/Qwen3-Coder-Next-GGUF",
      "path": "UD-Q5_K_XL/Qwen3-Coder-Next-UD-Q5_K_XL.gguf"
    }
  },
  {
    "id": "hf:unsloth/Qwen3-Coder-Next-GGUF:Q6_K",
    "family": "Qwen3-Coder-Next",
    "name": "Qwen3-Coder-Next",
    "task": "code",
    "quant": "Q6_K",
    "sizeBytes": 65613992288,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "unsloth/Qwen3-Coder-Next-GGUF",
      "path": "Q6_K/Qwen3-Coder-Next-Q6_K.gguf"
    }
  },
  {
    "id": "hf:unsloth/Qwen3-Coder-Next-GGUF:Q6_K_XL",
    "family": "Qwen3-Coder-Next",
    "name": "Qwen3-Coder-Next",
    "task": "code",
    "quant": "Q6_K_XL",
    "sizeBytes": 73118769504,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "unsloth/Qwen3-Coder-Next-GGUF",
      "path": "UD-Q6_K_XL/Qwen3-Coder-Next-UD-Q6_K_XL.gguf"
    }
  },
  {
    "id": "hf:unsloth/Qwen3-Coder-Next-GGUF:Q8_0",
    "family": "Qwen3-Coder-Next",
    "name": "Qwen3-Coder-Next",
    "task": "code",
    "quant": "Q8_0",
    "sizeBytes": 84812255584,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "unsloth/Qwen3-Coder-Next-GGUF",
      "path": "Q8_0/Qwen3-Coder-Next-Q8_0.gguf"
    }
  },
  {
    "id": "hf:unsloth/Qwen3-Coder-Next-GGUF:Q8_K_XL",
    "family": "Qwen3-Coder-Next",
    "name": "Qwen3-Coder-Next",
    "task": "code",
    "quant": "Q8_K_XL",
    "sizeBytes": 86348747104,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "unsloth/Qwen3-Coder-Next-GGUF",
      "path": "UD-Q8_K_XL/Qwen3-Coder-Next-UD-Q8_K_XL.gguf"
    }
  },
  {
    "id": "hf:yuxinlu1/gemma-4-12B-coder-fable5-composer2.5-v1-GGUF:Q2_K",
    "family": "gemma-4-12B-coder-fable5-composer2.5-v1",
    "name": "gemma-4-12B-coder-fable5-composer2.5-v1",
    "task": "code",
    "params": 12,
    "quant": "Q2_K",
    "sizeBytes": 4830147104,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "yuxinlu1/gemma-4-12B-coder-fable5-composer2.5-v1-GGUF",
      "path": "gemma4-coding-Q2_K.gguf"
    }
  },
  {
    "id": "hf:yuxinlu1/gemma-4-12B-coder-fable5-composer2.5-v1-GGUF:Q3_K_M",
    "family": "gemma-4-12B-coder-fable5-composer2.5-v1",
    "name": "gemma-4-12B-coder-fable5-composer2.5-v1",
    "task": "code",
    "params": 12,
    "quant": "Q3_K_M",
    "sizeBytes": 6087086624,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "yuxinlu1/gemma-4-12B-coder-fable5-composer2.5-v1-GGUF",
      "path": "gemma4-coding-Q3_K_M.gguf"
    }
  },
  {
    "id": "hf:yuxinlu1/gemma-4-12B-coder-fable5-composer2.5-v1-GGUF:Q4_K_M",
    "family": "gemma-4-12B-coder-fable5-composer2.5-v1",
    "name": "gemma-4-12B-coder-fable5-composer2.5-v1",
    "task": "code",
    "params": 12,
    "quant": "Q4_K_M",
    "sizeBytes": 7381381664,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "yuxinlu1/gemma-4-12B-coder-fable5-composer2.5-v1-GGUF",
      "path": "gemma4-coding-Q4_K_M.gguf"
    }
  },
  {
    "id": "hf:yuxinlu1/gemma-4-12B-coder-fable5-composer2.5-v1-GGUF:Q6_K",
    "family": "gemma-4-12B-coder-fable5-composer2.5-v1",
    "name": "gemma-4-12B-coder-fable5-composer2.5-v1",
    "task": "code",
    "params": 12,
    "quant": "Q6_K",
    "sizeBytes": 9786020384,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "yuxinlu1/gemma-4-12B-coder-fable5-composer2.5-v1-GGUF",
      "path": "gemma4-coding-Q6_K.gguf"
    }
  },
  {
    "id": "hf:yuxinlu1/gemma-4-12B-coder-fable5-composer2.5-v1-GGUF:Q8_0",
    "family": "gemma-4-12B-coder-fable5-composer2.5-v1",
    "name": "gemma-4-12B-coder-fable5-composer2.5-v1",
    "task": "code",
    "params": 12,
    "quant": "Q8_0",
    "sizeBytes": 12669645344,
    "modalities": [
      "text"
    ],
    "source": {
      "provider": "huggingface",
      "repo": "yuxinlu1/gemma-4-12B-coder-fable5-composer2.5-v1-GGUF",
      "path": "gemma4-coding-Q8_0.gguf"
    }
  }
];
