// Generate a static catalog snapshot from Hugging Face so the widget has real,
// current data without a live fetch (with live fetch as the fallback — the plan's
// hybrid). Reuses the same provider the browser uses. Run:
//   node scripts/build-catalog.mjs
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
// Import the provider directly (not the package index) — the index re-exports the
// snapshot module we're about to generate, which would be a bootstrap cycle.
import { huggingFaceCatalogProvider } from "../packages/catalog-huggingface/src/provider.js";

const here = dirname(fileURLToPath(import.meta.url));
const OUT = join(here, "..", "packages", "catalog-huggingface", "src", "snapshot-data.js");

// A spread across the workloads the widget cares about. Deduped by variant id.
const QUERIES = [
  { task: "code", query: "coder", limit: 6 },
  { task: "chat", query: "instruct", limit: 6 },
  { task: "reasoning", query: "reasoning", limit: 4 },
];

const byId = new Map();
for (const q of QUERIES) {
  try {
    const variants = await huggingFaceCatalogProvider(q).list();
    for (const v of variants) if (!byId.has(v.id)) byId.set(v.id, v);
  } catch (e) {
    console.warn(`query ${JSON.stringify(q)} failed: ${e.message}`);
  }
}

const snapshot = [...byId.values()].sort((a, b) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0));
const banner =
  "// GENERATED by scripts/build-catalog.mjs — do not edit by hand.\n" +
  "// Source: Hugging Face public API. Re-run the script to refresh.\n";
const body =
  banner +
  `export const GENERATED_AT = ${JSON.stringify(new Date().toISOString())};\n` +
  `export const SNAPSHOT = ${JSON.stringify(snapshot, null, 2)};\n`;

writeFileSync(OUT, body);
console.log(`Wrote ${snapshot.length} variants across ${byId.size} ids to ${OUT}`);
